In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("spam_ham_dataset.csv")

In [4]:
df.head()

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0

In [5]:
df.isnull().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [10]:
df['label'].value_counts()

ham     3672
spam    1499
Name: label, dtype: int64

In [8]:
print(df.columns.tolist())

['Unnamed: 0', 'label', 'text', 'label_num']

In [9]:
df.head()

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0

In [11]:
df['label'] = df['label'].map({'ham' : 0 , 'spam' : 1})

In [12]:
df.head()

,Unnamed: 0,label,text,label_num
0,605,0,Subject: enron methanol ; meter # : 988291\r\n...,0
1,2349,0,"Subject: hpl nom for january 9 , 2001\r\n( see...",0
2,3624,0,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0
3,4685,1,"Subject: photoshop , windows , office . cheap ...",1
4,2030,0,Subject: re : indian springs\r\nthis deal is t...,0

In [13]:
# Data split into x and y

x = df[['text']]
y = df['label']

In [14]:
x

                                                   text
0     Subject: enron methanol ; meter # : 988291\r\n...
1     Subject: hpl nom for january 9 , 2001\r\n( see...
2     Subject: neon retreat\r\nho ho ho , we ' re ar...
3     Subject: photoshop , windows , office . cheap ...
4     Subject: re : indian springs\r\nthis deal is t...
...                                                 ...
5166  Subject: put the 10 on the ft\r\nthe transport...
5167  Subject: 3 / 4 / 2000 and following noms\r\nhp...
5168  Subject: calpine daily gas nomination\r\n>\r\n...
5169  Subject: industrial worksheets for august 2000...
5170  Subject: important online banking alert\r\ndea...

[5171 rows x 1 columns]

In [15]:
y

0       0
1       0
2       0
3       1
4       0
       ..
5166    0
5167    0
5168    0
5169    0
5170    1
Name: label, Length: 5171, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 42)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [20]:
preprocessor = ColumnTransformer(transformers = [
    ("txt" , CountVectorizer() , 'text')
    ])

In [21]:
clf = Pipeline(steps = [
    ("preprocessing" , preprocessor),
    ("classifier" , MultinomialNB())
    
])

In [22]:
clf.fit(x_train , y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('txt', CountVectorizer(),
                                                  'text')])),
                ('classifier', MultinomialNB())])

In [23]:
clf.score(x_test,y_test)

0.9719806763285024

In [24]:
pred = clf.predict(x_test)

In [25]:
from sklearn.metrics import classification_report

In [26]:
print(classification_report(y_test , pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       742
           1       0.96      0.95      0.95       293

    accuracy                           0.97      1035
   macro avg       0.97      0.96      0.97      1035
weighted avg       0.97      0.97      0.97      1035

In [29]:
# Prediction on new Data:
emails = pd.DataFrame({
    "text" :["Hey buddy, can we get together to watch cricket match tomorrow ?",
            "upto 40% discount on parking , exclusive offer just for you. don't miss."]
})

In [30]:
clf.predict(emails)

array([0, 1], dtype=int64)